repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/
      - id: ruff-format
        files: ^backend/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: prettier
        name: prettier --write (webapp)
        entry: webapp/node_modules/.bin/prettier --write
        language: system
        files: ^webapp/.*\.(ts|vue|css)$
        pass_filenames: true

      - id: eslint
        name: eslint --fix (webapp)
        entry: webapp/node_modules/.bin/eslint --fix --config webapp/eslint.config.js
        language: system
        files: ^webapp/.*\.(ts|vue)$
        pass_filenames: true
