"""resume_analyses and ats_scores

Revision ID: 06abe39a184c
Revises: eca96043348e
Create Date: 2026-08-14 19:19:57.643197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06abe39a184c"
down_revision: Union[str, None] = "eca96043348e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ai_job_status is a new enum type introduced by this migration, used by
# both tables below. resume_analyses' status column (first table created)
# is the one that actually emits CREATE TYPE; ats_scores' status column
# reuses the same type via create_type=False. Autogenerate doesn't
# reliably render create_type=False into the migration script even
# though app/models/ats_score.py's _ai_job_status_enum sets it - same
# "needs a manual nudge" gotcha BACKEND_SUMMARY.md documents for
# application_status_history's migration (confirmed the same way: the
# raw autogenerated output here rendered ats_scores' column as a plain
# postgresql.ENUM(...) with no create_type=False at all, which would
# have re-run CREATE TYPE ai_job_status and failed with DuplicateObject).
_ai_job_status_enum_existing = postgresql.ENUM(
    "pending",
    "processing",
    "completed",
    "failed",
    name="ai_job_status",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume_analyses",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "processing", "completed", "failed", name="ai_job_status"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column(
            "parsed_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resume_analyses_document_id"),
        "resume_analyses",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resume_analyses_user_id"), "resume_analyses", ["user_id"], unique=False
    )
    op.create_table(
        "ats_scores",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resume_analysis_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=True),
        sa.Column("job_description", sa.Text(), nullable=True),
        sa.Column("job_description_source", sa.String(length=16), nullable=True),
        sa.Column(
            "status",
            _ai_job_status_enum_existing,
            server_default="pending",
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resume_analysis_id"], ["resume_analyses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ats_scores_application_id"),
        "ats_scores",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ats_scores_resume_analysis_id"),
        "ats_scores",
        ["resume_analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ats_scores_user_id"), "ats_scores", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ats_scores_user_id"), table_name="ats_scores")
    op.drop_index(op.f("ix_ats_scores_resume_analysis_id"), table_name="ats_scores")
    op.drop_index(op.f("ix_ats_scores_application_id"), table_name="ats_scores")
    op.drop_table("ats_scores")
    op.drop_index(op.f("ix_resume_analyses_user_id"), table_name="resume_analyses")
    op.drop_index(op.f("ix_resume_analyses_document_id"), table_name="resume_analyses")
    op.drop_table("resume_analyses")
    # ### end Alembic commands ###
    # Both tables' status columns are gone now, but the enum type itself
    # isn't dropped by DROP TABLE in Postgres - drop it explicitly so a
    # downgrade -> upgrade cycle doesn't hit "type ai_job_status already
    # exists" on the re-upgrade.
    _ai_job_status_enum_existing.drop(op.get_bind(), checkfirst=True)
