"""interview reminders and user timezone

Revision ID: d65db92902b9
Revises: 37f704e60528
Create Date: 2026-08-10 21:41:40.365764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d65db92902b9"
down_revision: Union[str, None] = "37f704e60528"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- users.timezone --------------------------------------------------
    op.add_column("users", sa.Column("timezone", sa.String(length=64), nullable=True))

    # --- interview_reminders ---------------------------------------------
    op.create_table(
        "interview_reminders",
        sa.Column("interview_id", sa.UUID(), nullable=False),
        sa.Column("remind_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "channel",
            sa.Enum("email", "push", name="reminder_channel"),
            server_default="email",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"], ["interviews.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_reminders_interview_id"),
        "interview_reminders",
        ["interview_id"],
        unique=False,
    )

    # Composite-ish access pattern the beat task's query uses every run
    # (remind_at <= now() AND sent_at IS NULL) - index remind_at directly
    # rather than relying on a full scan every 5-15 minutes.
    op.create_index(
        op.f("ix_interview_reminders_remind_at"),
        "interview_reminders",
        ["remind_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    op.drop_index(
        op.f("ix_interview_reminders_remind_at"), table_name="interview_reminders"
    )
    op.drop_index(
        op.f("ix_interview_reminders_interview_id"), table_name="interview_reminders"
    )
    op.drop_table("interview_reminders")
    # ### end Alembic commands ###
