"""application_status_history

Revision ID: eca96043348e
Revises: 873b7c6fdc36
Create Date: 2026-08-13 21:40:04.345166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "eca96043348e"
down_revision: Union[str, None] = "873b7c6fdc36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_application_status_enum = postgresql.ENUM(
    "saved",
    "applied",
    "phone_screen",
    "interviewing",
    "offer",
    "rejected",
    "withdrawn",
    "accepted",
    name="application_status",
    create_type=False,
)


def upgrade() -> None:
    op.create_table(
        "application_status_history",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("from_status", _application_status_enum, nullable=True),
        sa.Column("to_status", _application_status_enum, nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_status_history_application_id"),
        "application_status_history",
        ["application_id"],
        unique=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_application_status_history_application_id"),
        table_name="application_status_history",
    )
    op.drop_table("application_status_history")
    # ### end Alembic commands ###
